package generator_test

import (
	"fmt"
	"sort"

	"github.com/steffnova/go-check/constraints"
	"github.com/steffnova/go-check/generator"
)

// This example demonstrates how to use Int() generator and Map combinator to build a generator
// for generation of even integer numbers. Each generated int value by Int() generator will be
// multiplied by 2 by mapper.
func ExampleGenerator_Map_evenInt() {
	streamer := generator.Streamer(
		func(n int) {
			fmt.Printf("%d\n", n)
		},
		generator.Int(constraints.Int{
			Min: 0,
			Max: 100,
		}).Map(func(n int) int {
			return n * 2
		}),
	)

	if err := generator.Stream(0, 10, streamer); err != nil {
		panic(err)
	}
	// Output:
	// 62
	// 32
	// 160
	// 172
	// 138
	// 44
	// 168
	// 6
	// 128
	// 60
}

// This example demonstrates how to use Slice(Int()) generator and Map combinator to build a generator
// for generation slice of ordered intger numbers. Each generated []int value by Slice(Int()) generator
// will be sorted by mapper.
func ExampleGenerator_Map_orderedIntSlice() {
	streamer := generator.Streamer(
		func(n []int) {
			fmt.Printf("%d\n", n)
		},

		generator.Slice(
			generator.Int(constraints.Int{
				Min: 0,
				Max: 10000,
			}),
			constraints.Length{
				Min: 0,
				Max: 10,
			}).Map(func(ns []int) []int {
			sort.SliceStable(ns, func(i, j int) bool {
				return ns[i] < ns[j]
			})
			return ns
		}),
	)

	if err := generator.Stream(0, 10, streamer); err != nil {
		panic(err)
	}

	// Output:
	// [259 1069 1984 5150 5910]
	// [3323]
	// [2140 3257 3378 5063 5836 8213 8701 9832]
	// [1247 3422 4175 4605 4904 5523 5629 5705 9029 9609]
	// [1943 3465 4132 8913]
	// [30 2361 3384 6926]
	// []
	// [271 1007 2281 8190 8477 9452]
	// [3746 5588 8797 9599]
	// [19 697 3795 5496 6269 6795 7065 7552]
}

// This example demonstrates how to use Int() generator and Filter combinator to build a generator
// for generation of even integer numbers. Int values generated by Int() generator that are divisable
// by 2 will be filtered by Filter combinator.
func ExampleGenerator_Filter_evenInt() {
	streamer := generator.Streamer(
		func(n int) {
			fmt.Printf("%d\n", n)
		},
		generator.Int(constraints.Int{
			Min: 0,
			Max: 100,
		},
		).Filter(func(n int) bool {
			return n%2 == 0
		}),
	)

	if err := generator.Stream(0, 10, streamer); err != nil {
		panic(err)
	}
	// Output:
	// 16
	// 80
	// 86
	// 22
	// 84
	// 64
	// 30
	// 40
	// 62
	// 92
}

// This example demonstrates how to use Rune() generator and Bind() generator along with String() generator
// to build generator that generates string with single repeating character. Characters generated by Rune()
// generator will be used by Bind() combinator to setup rune constraints in String() generator returned by binder.
func ExampleGenerator_Bind_stringWithRepeatingCharacter() {
	streamer := generator.Streamer(
		func(s string) {
			fmt.Printf("%s\n", s)
		},
		generator.Rune(constraints.Rune{
			MinCodePoint: 'a',
			MaxCodePoint: 'z',
		}).Bind(func(c rune) generator.Generator {
			return generator.String(constraints.String{
				Rune: constraints.Rune{
					MinCodePoint: c,
					MaxCodePoint: c,
				},
				Length: constraints.Length{
					Min: 5,
					Max: 10,
				},
			})
		}),
	)

	if err := generator.Stream(0, 10, streamer); err != nil {
		panic(err)
	}
	// Output:
	// vvvvvvv
	// dddddddddd
	// jjjjjj
	// ooooo
	// bbbbbbbbbb
	// xxxxxxxxxx
	// aaaaaaaa
	// oooooo
	// wwwwwwwwww
	// ggggg
}
