package check

import (
	"fmt"
	"math/rand"
)

// Stream streams data using a streamer. Number of items generated by
// streamer and seed for RNG are defined by `config` parameter. Error
// is returned if streamer returns an error
func Stream(streamer streamer, config Config) error {
	random := Rng{
		Rand: rand.New(rand.NewSource(config.Seed)),
	}

	for i := int64(0); i < config.Iterations; i++ {
		if err := streamer(random); err != nil {
			return fmt.Errorf("failed to run stream: %s", err)
		}
	}

	return nil
}
